image:
  repository: matejcihlar/devops-project-frontend
  tag: latest
  pullPolicy: Always
  nameOverride: devops-showcase-frontend

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: devops-showcase-project.ovh
      paths:
        - path: "^/((?!api).*)$"
          pathType: ImplementationSpecific
  tls:
    - secretName: frontend-tls
      hosts:
        - devops-showcase-project.ovh