fullNameOverride: devops-showcase-frontend
image:
  repository: matejcihlar/devops-project-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 50m
    memory: 100Mi

service:
  type: ClusterIP
  port: 80