# Use official OpenJDK base image
FROM openjdk:17-jdk-slim

ENV SPRING_PROFILES_ACTIVE=default

# Set working directory in the container
WORKDIR /app

# Copy the Maven project file
COPY /backend/pom.xml .

# Copy the source code
COPY /backend/src ./src

# Install Maven
RUN apt-get update && \
    apt-get install -y maven && \
    apt-get clean;

# Build the application
RUN mvn clean package -DskipTests

# Expose the application port
EXPOSE 90

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app/target/devops-project-backend-1.0.0-SNAPSHOT.jar"]