host: devops-showcase-project.ovh
ingressClassName: nginx
annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod

frontend:
  serviceName: devops-showcase-frontend
  servicePort: 80

backend:
  serviceName: devops-showcase-backend
  servicePort: 90