apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-showcase-ingress
  annotations:
    {{- toYaml .Values.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: devops-showcase-tls
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "backend.fullname" . }}
                port:
                  number: {{ .Values.backend.servicePort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "frontend.fullname" $ }}
                port:
                  number: {{ .Values.frontend.servicePort }}