apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  application.properties: |
    spring.profiles.active={{ .Values.env.SPRING_PROFILES_ACTIVE }}
    server.port=90