server:
  port: 90

spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"
      mapped-paths: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always