apiVersion: v2
name: devops-showcase-backend
description: Backend service for DevOps showcase project
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.20.0"

keywords:
  - backend
  - spring-boot
maintainers:
  - name: "Matěj"
    email: "matej@matej.com"