image:
  repository: matejcihlar/devops-project-backend
  tag: latest
  pullPolicy: Always
  nameOverride: devops-showcase-backend

replicaCount: 1

resources:
  limits:
    cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 300m
    memory: 512Mi

service:
  type: ClusterIP
  port: 90

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: devops-showcase-project.ovh
      paths:
        - path: /api
          pathType: Prefix
  tls:
    - secretName: backend-tls
      hosts:
        - devops-showcase-project.ovh