image:
  repository: matejcihlar/devops-project-backend
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

service:
  type: ClusterIP
  port: 90